/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Countries and their settings
         * @description Currency, locale, local today, closed weekdays (ISO, 7 = Sunday), rise colour (`up_is_pos`: rising prices shown green), default area, recent areas and watchlist, and the unit table (per-kg factor and decimals) for wholesale and retail.
         */
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{cc}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Areas of a country
         * @description Areas (district or city) with centre coordinates for straight-line distances, whether retail prices are reported, and the latest wholesale trade date with its freshness.
         */
        get: operations["areas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{cc}/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crops of a country
         * @description Names, category, variety, whether retail prices exist, default watchlist.
         */
        get: operations["crops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{crop}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare one crop across the areas of a country
         * @description Each area's latest price, market count, straight-line distance from the area being viewed, difference and rank (highest price first, ties share a rank, no data is not ranked). Sorting for display is left to the client.
         */
        get: operations["compare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{crop}/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wholesale markets of an area
         * @description Each market's latest price, distance from the area centre and its difference from the area median. Retail prices have no market breakdown.
         */
        get: operations["markets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{crop}/markets/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One wholesale market
         * @description Representative price (India: modal, Taiwan: average), change, the day's low–high range and the data source.
         */
        get: operations["market"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{crop}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quote of one crop in one area
         * @description Area price (wholesale: median of the markets that reported on the latest trade date), market count and range, change, indicators and a daily series with null for days without data. Without a price, `reason` says why. `nearby` names the highest and lowest price among this area and the 3 nearest other areas within 300 km that have a price on the same trade date.
         */
        get: operations["quote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Database status, the latest successful fetch of every data source and the running version (commit). Returns 503 `db_unavailable` when the database is down.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * International reference prices
         * @description Six World Bank Pink Sheet series (monthly averages, published early the next month), each with its latest month, the price per kg in the country's currency and the change from the month before. Every month is converted with the latest daily exchange rate (`fx`); `usd` keeps the published price. No local price comes with a `reason`.
         */
        get: operations["intl_prices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intl/{series}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One international reference price
         * @description The series with its 12 months up to the latest one (null = no price that month) and their high, low and average, all per kg in the country's currency.
         */
        get: operations["intl_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guess the user's area from the network address
         * @description Uses the leftmost public address of `X-Client-Forwarded-For` (set by the proxy from the Cloud Phone's `X-Forwarded-For`) and the nearest area centre within 300 km. No GPS; the address is neither stored nor logged. Nulls mean no guess.
         */
        get: operations["locate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Farm price news of a country
         * @description Up to 9 news items of the last 7 days: those mentioning the area (any of its names) first, then the newest first. `summary` is null when no summary could be made from the article; never invented. Updated once a day at 00:00 local time.
         */
        get: operations["news"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One news item
         * @description The item with its country and local today; 404 once it is older than 7 days.
         */
        get: operations["news_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prices of many crops in one area
         * @description For the home screen and crop lists: latest area price, change vs the previous trading day, freshness and a 7-day sparkline for each crop. `crops` is a comma-separated list (default: every crop); unknown crop ids are skipped.
         */
        get: operations["prices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaOut */
        AreaOut: {
            /** Has Retail */
            has_retail: boolean;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Latest Trade Date */
            latest_trade_date: string | null;
            /** Lon */
            lon: number;
            name: components["schemas"]["I18nText"];
            region: components["schemas"]["I18nText"];
            staleness: components["schemas"]["StalenessOut"];
        };
        /** AreasOut */
        AreasOut: {
            /** Areas */
            areas: components["schemas"]["AreaOut"][];
            /** Country */
            country: string;
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /**
         * ChangeOut
         * @description Latest vs the previous trading day with data; |pct| < 0.05% is flat.
         */
        ChangeOut: {
            /** Diff Per Kg */
            diff_per_kg: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "flat";
            /** Pct */
            pct: number;
            /** Prev Trade Date */
            prev_trade_date: string | null;
        };
        /** CompareOut */
        CompareOut: {
            /** Area Id */
            area_id: string;
            /** Crop Id */
            crop_id: string;
            /** Currency */
            currency: string;
            rank: components["schemas"]["RankOut"];
            /** Rows */
            rows: components["schemas"]["CompareRowOut"][];
            /**
             * Today
             * Format: date
             */
            today: string;
            /**
             * Type
             * @enum {string}
             */
            type: "wholesale" | "retail";
        };
        /** CompareRowOut */
        CompareRowOut: {
            /** Area Id */
            area_id: string;
            /**
             * Diff Per Kg
             * @description This area minus the area being viewed.
             */
            diff_per_kg: number | null;
            /**
             * Distance Km
             * @description Straight line between area centres (not road).
             */
            distance_km: number;
            /** Is Base */
            is_base: boolean;
            /** N Markets */
            n_markets: number;
            /** Price Per Kg */
            price_per_kg: number | null;
            /**
             * Rank
             * @description By price, highest first; equal prices share a rank.
             */
            rank: number | null;
            staleness: components["schemas"]["StalenessOut"];
            /** Trade Date */
            trade_date: string | null;
        };
        /** CountriesOut */
        CountriesOut: {
            /** Countries */
            countries: components["schemas"]["CountryOut"][];
        };
        /** CountryOut */
        CountryOut: {
            area_suffix: components["schemas"]["I18nText"];
            /** Closed Weekdays */
            closed_weekdays: number[];
            /** Code */
            code: string;
            coverage: components["schemas"]["I18nText"];
            /** Currency */
            currency: string;
            /** Default Area Id */
            default_area_id: string;
            /** Default Recent Area Ids */
            default_recent_area_ids: string[];
            /** Default Watch */
            default_watch: string[];
            /**
             * Estimated Price Types
             * @description Price types no source of this country reports, estimated from the other one (docs/06 §4). Every screen showing such a price must say it is an estimate.
             */
            estimated_price_types: string[];
            /** Locale */
            locale: string;
            name: components["schemas"]["I18nText"];
            rep_price_label: components["schemas"]["I18nText"];
            source_label: components["schemas"]["I18nText"];
            /**
             * Today
             * Format: date
             */
            today: string;
            units: components["schemas"]["UnitsOut"];
            /** Up Is Pos */
            up_is_pos: boolean;
            /** Utc Offset Min */
            utc_offset_min: number;
        };
        /** CropOut */
        CropOut: {
            /** Category */
            category: string;
            /** Default Watch */
            default_watch: boolean;
            /**
             * Estimate Ratio
             * @description What the estimated price type of this country is multiplied by for this crop (null when nothing is estimated), so a screen can name the ratio it shows.
             */
            estimate_ratio: number | null;
            /** Has Retail */
            has_retail: boolean;
            /** Id */
            id: string;
            name: components["schemas"]["I18nText"];
            variety: components["schemas"]["I18nText"];
        };
        /** CropsOut */
        CropsOut: {
            /** Country */
            country: string;
            /** Crops */
            crops: components["schemas"]["CropOut"][];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FxOut */
        FxOut: {
            /** Currency */
            currency: string;
            /**
             * Per Usd
             * @description Units of the currency for one US dollar.
             */
            per_usd: number;
            /**
             * Rate Date
             * Format: date
             * @description The rate's day as published by the provider (UTC).
             */
            rate_date: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Sources */
            sources: components["schemas"]["SourceStatusOut"][];
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * I18nText
         * @description Text in every supported language; switching language needs no refetch.
         */
        I18nText: {
            /** En */
            en: string;
            /** Zh-Tw */
            "zh-TW": string;
        };
        /**
         * IntlChangeOut
         * @description The latest month against the month before; |pct| < 0.05% is flat.
         */
        IntlChangeOut: {
            /**
             * Diff Per Kg
             * @description In the country's currency; null without a rate.
             */
            diff_per_kg: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "flat";
            /** Pct */
            pct: number;
            /**
             * Prev Month
             * Format: date
             */
            prev_month: string;
        };
        /** IntlItemOut */
        IntlItemOut: {
            /** Category */
            category: string;
            change: components["schemas"]["IntlChangeOut"] | null;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /**
             * Month
             * @description First day of the latest month with a price.
             */
            month: string | null;
            name: components["schemas"]["I18nText"];
            /** Price Per Kg */
            price_per_kg: number | null;
            /**
             * Reason
             * @description Why there is no local price: no_data (no month yet) or no_fx (no rate).
             */
            reason: ("no_data" | "no_fx") | null;
            /**
             * Source Name
             * @description The series as the World Bank names it.
             */
            source_name: string;
            /** @description Grade or origin, e.g. Thai 5% broken. */
            spec: components["schemas"]["I18nText"];
            /**
             * Usd
             * @description The published monthly average, US$ per `usd_unit`.
             */
            usd: number | null;
            /**
             * Usd Unit
             * @enum {string}
             */
            usd_unit: "mt" | "kg";
        };
        /** IntlPointOut */
        IntlPointOut: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Price Per Kg */
            price_per_kg: number | null;
            /** Usd */
            usd: number | null;
        };
        /** IntlPricesOut */
        IntlPricesOut: {
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            /** @description The rate every month is converted with. */
            fx: components["schemas"]["FxOut"] | null;
            /** Items */
            items: components["schemas"]["IntlItemOut"][];
            /**
             * Published
             * @description Update date of the World Bank file.
             */
            published: string | null;
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /** IntlSeriesOut */
        IntlSeriesOut: {
            /** Category */
            category: string;
            change: components["schemas"]["IntlChangeOut"] | null;
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            fx: components["schemas"]["FxOut"] | null;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /**
             * Month
             * @description First day of the latest month with a price.
             */
            month: string | null;
            name: components["schemas"]["I18nText"];
            /** Price Per Kg */
            price_per_kg: number | null;
            /** Published */
            published: string | null;
            /**
             * Reason
             * @description Why there is no local price: no_data (no month yet) or no_fx (no rate).
             */
            reason: ("no_data" | "no_fx") | null;
            /**
             * Series
             * @description The 12 months up to `month`, oldest first; null = no price that month.
             */
            series: components["schemas"]["IntlPointOut"][];
            /**
             * Source Name
             * @description The series as the World Bank names it.
             */
            source_name: string;
            /** @description Grade or origin, e.g. Thai 5% broken. */
            spec: components["schemas"]["I18nText"];
            stats: components["schemas"]["IntlStatsOut"];
            /**
             * Today
             * Format: date
             */
            today: string;
            /**
             * Usd
             * @description The published monthly average, US$ per `usd_unit`.
             */
            usd: number | null;
            /**
             * Usd Unit
             * @enum {string}
             */
            usd_unit: "mt" | "kg";
        };
        /**
         * IntlStatsOut
         * @description Over the months of `series` that have a price.
         */
        IntlStatsOut: {
            /** Avg Per Kg */
            avg_per_kg: number | null;
            /** High Per Kg */
            high_per_kg: number | null;
            /** Low Per Kg */
            low_per_kg: number | null;
            /**
             * Vs Avg Pct
             * @description Latest price against the average.
             */
            vs_avg_pct: number | null;
        };
        /**
         * LocateOut
         * @description The guessed area, or nulls when there is no guess.
         */
        LocateOut: {
            /** Area Id */
            area_id: string | null;
            /** Country */
            country: string | null;
        };
        /** MarketOut */
        MarketOut: {
            /** Area Id */
            area_id: string;
            change: components["schemas"]["ChangeOut"] | null;
            /** Crop Id */
            crop_id: string;
            /** Currency */
            currency: string;
            /** Fetched At */
            fetched_at: string | null;
            /** High Per Kg */
            high_per_kg: number | null;
            /** Km From Center */
            km_from_center: number | null;
            /** Low Per Kg */
            low_per_kg: number | null;
            /** Market Id */
            market_id: string;
            name: components["schemas"]["I18nText"];
            /** Price Per Kg */
            price_per_kg: number | null;
            /** Reason */
            reason: "no_data" | null;
            source: components["schemas"]["SourceOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Trade Date */
            trade_date: string | null;
        };
        /** MarketRowOut */
        MarketRowOut: {
            /**
             * Diff Per Kg
             * @description Market price minus the area median.
             */
            diff_per_kg: number | null;
            /** Km From Center */
            km_from_center: number | null;
            /** Market Id */
            market_id: string;
            name: components["schemas"]["I18nText"];
            /** Price Per Kg */
            price_per_kg: number | null;
            staleness: components["schemas"]["StalenessOut"];
            /** Trade Date */
            trade_date: string | null;
        };
        /** MarketsOut */
        MarketsOut: {
            /** Area Id */
            area_id: string;
            /** Crop Id */
            crop_id: string;
            /** Currency */
            currency: string;
            /** Median Per Kg */
            median_per_kg: number | null;
            /** Rows */
            rows: components["schemas"]["MarketRowOut"][];
            staleness: components["schemas"]["StalenessOut"];
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Trade Date */
            trade_date: string | null;
        };
        /** MarketsSummaryOut */
        MarketsSummaryOut: {
            /**
             * Count
             * @description Markets with a price on the latest trade date.
             */
            count: number;
            /** Max Per Kg */
            max_per_kg: number | null;
            /** Min Per Kg */
            min_per_kg: number | null;
            /**
             * Total
             * @description All markets of the area.
             */
            total: number;
        };
        /** NearbyAreaOut */
        NearbyAreaOut: {
            /** Area Id */
            area_id: string;
            /**
             * Diff Per Kg
             * @description This area minus the area being viewed (0 for it).
             */
            diff_per_kg: number;
            /**
             * Distance Km
             * @description Straight line from the viewed area (0 for it).
             */
            distance_km: number;
            /**
             * Is Base
             * @description The viewed area itself: nothing nearby is higher (lower).
             */
            is_base: boolean;
            /** Price Per Kg */
            price_per_kg: number;
        };
        /**
         * NearbyOut
         * @description Highest and lowest price among the viewed area and the 3 nearest other areas within
         *     300 km that have a price on the same trade date; ties go to the viewed area.
         */
        NearbyOut: {
            highest: components["schemas"]["NearbyAreaOut"];
            lowest: components["schemas"]["NearbyAreaOut"];
        };
        /** NewsItemDetailOut */
        NewsItemDetailOut: {
            /**
             * Area Ids
             * @description Areas the title or summary mention.
             */
            area_ids: string[];
            /** Country */
            country: string;
            /**
             * Crop Ids
             * @description Related crops of the country, most related first.
             */
            crop_ids: string[];
            /**
             * Days Ago
             * @description 0 = today, 1 = yesterday… (local dates).
             */
            days_ago: number;
            /** Id */
            id: number;
            /**
             * Lang
             * @description Language of the title: `zh-TW`, `en`, `ms`…
             */
            lang: string;
            /**
             * Published At
             * Format: date-time
             * @description In the country's own UTC offset.
             */
            published_at: string;
            /**
             * Published Date
             * Format: date
             * @description Local date of publication.
             */
            published_date: string;
            source: components["schemas"]["NewsSourceOut"];
            /**
             * Summary
             * @description Two sentences written by a model from the article; null when there is none (then show the title, source and date only).
             */
            summary: string | null;
            /** Summary Lang */
            summary_lang: string | null;
            /** Title */
            title: string;
            /**
             * Today
             * Format: date
             */
            today: string;
            /**
             * Url
             * @description Publisher's URL when known. The app does not open it.
             */
            url: string;
        };
        /** NewsItemOut */
        NewsItemOut: {
            /**
             * Area Ids
             * @description Areas the title or summary mention.
             */
            area_ids: string[];
            /**
             * Crop Ids
             * @description Related crops of the country, most related first.
             */
            crop_ids: string[];
            /**
             * Days Ago
             * @description 0 = today, 1 = yesterday… (local dates).
             */
            days_ago: number;
            /** Id */
            id: number;
            /**
             * Lang
             * @description Language of the title: `zh-TW`, `en`, `ms`…
             */
            lang: string;
            /**
             * Published At
             * Format: date-time
             * @description In the country's own UTC offset.
             */
            published_at: string;
            /**
             * Published Date
             * Format: date
             * @description Local date of publication.
             */
            published_date: string;
            source: components["schemas"]["NewsSourceOut"];
            /**
             * Summary
             * @description Two sentences written by a model from the article; null when there is none (then show the title, source and date only).
             */
            summary: string | null;
            /** Summary Lang */
            summary_lang: string | null;
            /** Title */
            title: string;
            /**
             * Url
             * @description Publisher's URL when known. The app does not open it.
             */
            url: string;
        };
        /** NewsOut */
        NewsOut: {
            /** Area Id */
            area_id: string;
            /** Country */
            country: string;
            /**
             * Fetched At
             * @description End of the latest successful news run.
             */
            fetched_at: string | null;
            /**
             * Items
             * @description At most 9: items mentioning the area first, then the newest first.
             */
            items: components["schemas"]["NewsItemOut"][];
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /** NewsSourceOut */
        NewsSourceOut: {
            /**
             * Domain
             * @description Publisher's domain, e.g. `news.pts.org.tw`.
             */
            domain: string | null;
            /**
             * Name
             * @description Publisher, as Google News names it.
             */
            name: string;
        };
        /** PriceItemOut */
        PriceItemOut: {
            change: components["schemas"]["ChangeOut"] | null;
            /** Crop Id */
            crop_id: string;
            /** Price Per Kg */
            price_per_kg: number | null;
            /**
             * Reason
             * @description Why there is no price (null when there is one).
             */
            reason: ("no_retail_area" | "no_retail_crop" | "no_data") | null;
            /**
             * Spark
             * @description Last 7 calendar days; null = no data.
             */
            spark: (number | null)[];
            staleness: components["schemas"]["StalenessOut"];
            /** Trade Date */
            trade_date: string | null;
        };
        /** PricesOut */
        PricesOut: {
            /** Area Id */
            area_id: string;
            /** Country */
            country: string;
            /** Currency */
            currency: string;
            /** Fetched At */
            fetched_at: string | null;
            /** Items */
            items: components["schemas"]["PriceItemOut"][];
            /**
             * Today
             * Format: date
             */
            today: string;
            /**
             * Type
             * @enum {string}
             */
            type: "wholesale" | "retail";
        };
        /** QuoteOut */
        QuoteOut: {
            /** Area Id */
            area_id: string;
            change: components["schemas"]["ChangeOut"] | null;
            /** Crop Id */
            crop_id: string;
            /** Currency */
            currency: string;
            /** Fetched At */
            fetched_at: string | null;
            /** @description Wholesale only. */
            markets: components["schemas"]["MarketsSummaryOut"] | null;
            /** @description Null when the viewed area's price is missing or old, when no nearby area has a price on the same trade date, or when they all have the same price. */
            nearby: components["schemas"]["NearbyOut"] | null;
            /** Price Per Kg */
            price_per_kg: number | null;
            /** Reason */
            reason: ("no_retail_area" | "no_retail_crop" | "no_data") | null;
            /** Series */
            series: components["schemas"]["SeriesPointOut"][];
            source: components["schemas"]["SourceOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
            stats: components["schemas"]["StatsOut"];
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Trade Date */
            trade_date: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "wholesale" | "retail";
        };
        /** RankOut */
        RankOut: {
            /** Position */
            position: number | null;
            /** Total */
            total: number;
        };
        /** SeriesPointOut */
        SeriesPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price Per Kg */
            price_per_kg: number | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: string;
            name: components["schemas"]["I18nText"];
        };
        /** SourceStatusOut */
        SourceStatusOut: {
            /**
             * Last Success At
             * Format: date-time
             */
            last_success_at: string;
            /** Rows Ok */
            rows_ok: number;
            /** Source */
            source: string;
        };
        /**
         * StalenessOut
         * @description today · closed (only closed days since) · stale · none (nothing in 30 days).
         */
        StalenessOut: {
            /** Days */
            days: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "today" | "closed" | "stale" | "none";
        };
        /** StatsOut */
        StatsOut: {
            /** Arrivals */
            arrivals: ("low" | "normal" | "high") | null;
            /** Arrivals Ratio */
            arrivals_ratio: number | null;
            /** Change7 Pct */
            change7_pct: number | null;
            /** Change30 Pct */
            change30_pct: number | null;
            /** High7 Per Kg */
            high7_per_kg: number | null;
            /** High30 Per Kg */
            high30_per_kg: number | null;
            /** Low7 Per Kg */
            low7_per_kg: number | null;
            /** Low30 Per Kg */
            low30_per_kg: number | null;
            /**
             * Pos30
             * @description 0 = 30-day low, 1 = 30-day high.
             */
            pos30: number | null;
            /** Volatility */
            volatility: ("low" | "mid" | "high") | null;
            /** Volatility Pct */
            volatility_pct: number | null;
            /** Vs Avg7 Pct */
            vs_avg7_pct: number | null;
        };
        /** UnitOptionOut */
        UnitOptionOut: {
            /** Decimals */
            decimals: number;
            /** Id */
            id: string;
            label: components["schemas"]["I18nText"];
            /** Per Kg */
            per_kg: number;
        };
        /** UnitSetOut */
        UnitSetOut: {
            /** Default */
            default: string;
            /** Options */
            options: components["schemas"]["UnitOptionOut"][];
        };
        /** UnitsOut */
        UnitsOut: {
            retail: components["schemas"]["UnitSetOut"];
            wholesale: components["schemas"]["UnitSetOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAreaOut = components['schemas']['AreaOut'];
export type SchemaAreasOut = components['schemas']['AreasOut'];
export type SchemaChangeOut = components['schemas']['ChangeOut'];
export type SchemaCompareOut = components['schemas']['CompareOut'];
export type SchemaCompareRowOut = components['schemas']['CompareRowOut'];
export type SchemaCountriesOut = components['schemas']['CountriesOut'];
export type SchemaCountryOut = components['schemas']['CountryOut'];
export type SchemaCropOut = components['schemas']['CropOut'];
export type SchemaCropsOut = components['schemas']['CropsOut'];
export type SchemaErrorBody = components['schemas']['ErrorBody'];
export type SchemaErrorOut = components['schemas']['ErrorOut'];
export type SchemaFxOut = components['schemas']['FxOut'];
export type SchemaHealthOut = components['schemas']['HealthOut'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaI18nText = components['schemas']['I18nText'];
export type SchemaIntlChangeOut = components['schemas']['IntlChangeOut'];
export type SchemaIntlItemOut = components['schemas']['IntlItemOut'];
export type SchemaIntlPointOut = components['schemas']['IntlPointOut'];
export type SchemaIntlPricesOut = components['schemas']['IntlPricesOut'];
export type SchemaIntlSeriesOut = components['schemas']['IntlSeriesOut'];
export type SchemaIntlStatsOut = components['schemas']['IntlStatsOut'];
export type SchemaLocateOut = components['schemas']['LocateOut'];
export type SchemaMarketOut = components['schemas']['MarketOut'];
export type SchemaMarketRowOut = components['schemas']['MarketRowOut'];
export type SchemaMarketsOut = components['schemas']['MarketsOut'];
export type SchemaMarketsSummaryOut = components['schemas']['MarketsSummaryOut'];
export type SchemaNearbyAreaOut = components['schemas']['NearbyAreaOut'];
export type SchemaNearbyOut = components['schemas']['NearbyOut'];
export type SchemaNewsItemDetailOut = components['schemas']['NewsItemDetailOut'];
export type SchemaNewsItemOut = components['schemas']['NewsItemOut'];
export type SchemaNewsOut = components['schemas']['NewsOut'];
export type SchemaNewsSourceOut = components['schemas']['NewsSourceOut'];
export type SchemaPriceItemOut = components['schemas']['PriceItemOut'];
export type SchemaPricesOut = components['schemas']['PricesOut'];
export type SchemaQuoteOut = components['schemas']['QuoteOut'];
export type SchemaRankOut = components['schemas']['RankOut'];
export type SchemaSeriesPointOut = components['schemas']['SeriesPointOut'];
export type SchemaSourceOut = components['schemas']['SourceOut'];
export type SchemaSourceStatusOut = components['schemas']['SourceStatusOut'];
export type SchemaStalenessOut = components['schemas']['StalenessOut'];
export type SchemaStatsOut = components['schemas']['StatsOut'];
export type SchemaUnitOptionOut = components['schemas']['UnitOptionOut'];
export type SchemaUnitSetOut = components['schemas']['UnitSetOut'];
export type SchemaUnitsOut = components['schemas']['UnitsOut'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "countries": [
                     *         {
                     *           "area_suffix": {
                     *             "en": " district",
                     *             "zh-TW": " 縣"
                     *           },
                     *           "closed_weekdays": [
                     *             7
                     *           ],
                     *           "code": "IN",
                     *           "coverage": {
                     *             "en": "6 states, 11 districts",
                     *             "zh-TW": "6 個邦、11 個縣"
                     *           },
                     *           "currency": "INR",
                     *           "default_area_id": "nashik",
                     *           "default_recent_area_ids": [
                     *             "nashik",
                     *             "pune",
                     *             "ahmednagar"
                     *           ],
                     *           "default_watch": [
                     *             "onion",
                     *             "tomato",
                     *             "potato"
                     *           ],
                     *           "locale": "en-IN",
                     *           "name": {
                     *             "en": "India",
                     *             "zh-TW": "印度"
                     *           },
                     *           "rep_price_label": {
                     *             "en": "Modal price",
                     *             "zh-TW": "常見價"
                     *           },
                     *           "source_label": {
                     *             "en": "Agmarknet",
                     *             "zh-TW": "Agmarknet・消費者事務部（印度政府）"
                     *           },
                     *           "today": "2026-09-19",
                     *           "units": {
                     *             "retail": {
                     *               "default": "kg",
                     *               "options": [
                     *                 {
                     *                   "decimals": 1,
                     *                   "id": "kg",
                     *                   "label": {
                     *                     "en": "₹/kg",
                     *                     "zh-TW": "₹/公斤"
                     *                   },
                     *                   "per_kg": 1
                     *                 },
                     *                 {
                     *                   "decimals": 0,
                     *                   "id": "qtl",
                     *                   "label": {
                     *                     "en": "₹/qtl",
                     *                     "zh-TW": "₹/公擔"
                     *                   },
                     *                   "per_kg": 100
                     *                 }
                     *               ]
                     *             },
                     *             "wholesale": {
                     *               "default": "qtl",
                     *               "options": [
                     *                 {
                     *                   "decimals": 0,
                     *                   "id": "qtl",
                     *                   "label": {
                     *                     "en": "₹/qtl",
                     *                     "zh-TW": "₹/公擔"
                     *                   },
                     *                   "per_kg": 100
                     *                 },
                     *                 {
                     *                   "decimals": 1,
                     *                   "id": "kg",
                     *                   "label": {
                     *                     "en": "₹/kg",
                     *                     "zh-TW": "₹/公斤"
                     *                   },
                     *                   "per_kg": 1
                     *                 }
                     *               ]
                     *             }
                     *           },
                     *           "up_is_pos": true,
                     *           "utc_offset_min": 330
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CountriesOut"];
                };
            };
        };
    };
    areas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Country code, e.g. `IN`, `TW` or `MY` */
                cc: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "areas": [
                     *         {
                     *           "has_retail": true,
                     *           "id": "nashik",
                     *           "lat": 20,
                     *           "latest_trade_date": "2026-09-19",
                     *           "lon": 73.79,
                     *           "name": {
                     *             "en": "Nashik",
                     *             "zh-TW": "Nashik"
                     *           },
                     *           "region": {
                     *             "en": "Maharashtra",
                     *             "zh-TW": "Maharashtra"
                     *           },
                     *           "staleness": {
                     *             "days": 0,
                     *             "state": "today"
                     *           }
                     *         },
                     *         {
                     *           "has_retail": false,
                     *           "id": "kolar",
                     *           "lat": 13.14,
                     *           "latest_trade_date": "2026-09-16",
                     *           "lon": 78.13,
                     *           "name": {
                     *             "en": "Kolar",
                     *             "zh-TW": "Kolar"
                     *           },
                     *           "region": {
                     *             "en": "Karnataka",
                     *             "zh-TW": "Karnataka"
                     *           },
                     *           "staleness": {
                     *             "days": 3,
                     *             "state": "stale"
                     *           }
                     *         }
                     *       ],
                     *       "country": "IN",
                     *       "today": "2026-09-19"
                     *     }
                     */
                    "application/json": components["schemas"]["AreasOut"];
                };
            };
            /** @description Country 'XX' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "country_not_found",
                     *         "message": "Country 'XX' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Country code, e.g. `IN`, `TW` or `MY` */
                cc: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "country": "IN",
                     *       "crops": [
                     *         {
                     *           "category": "veg",
                     *           "default_watch": true,
                     *           "has_retail": true,
                     *           "id": "onion",
                     *           "name": {
                     *             "en": "Onion",
                     *             "zh-TW": "洋蔥"
                     *           },
                     *           "variety": {
                     *             "en": "Red",
                     *             "zh-TW": "紅洋蔥"
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CropsOut"];
                };
            };
            /** @description Country 'XX' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "country_not_found",
                     *         "message": "Country 'XX' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare: {
        parameters: {
            query: {
                /** @description Area id */
                area: string;
                /** @description Country code */
                country: string;
                /** @description wholesale or retail */
                type?: "wholesale" | "retail";
            };
            header?: never;
            path: {
                /** @description Crop id */
                crop: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "crop_id": "onion",
                     *       "currency": "INR",
                     *       "rank": {
                     *         "position": 3,
                     *         "total": 10
                     *       },
                     *       "rows": [
                     *         {
                     *           "area_id": "delhi",
                     *           "diff_per_kg": 5.9,
                     *           "distance_km": 1017,
                     *           "is_base": false,
                     *           "n_markets": 2,
                     *           "price_per_kg": 29.4,
                     *           "rank": 1,
                     *           "staleness": {
                     *             "days": 0,
                     *             "state": "today"
                     *           },
                     *           "trade_date": "2026-09-19"
                     *         }
                     *       ],
                     *       "today": "2026-09-19",
                     *       "type": "wholesale"
                     *     }
                     */
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description type: Input should be 'wholesale' or 'retail' */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "type: Input should be 'wholesale' or 'retail'",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Area 'xyz' not found in IN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "area_not_found",
                     *         "message": "Area 'xyz' not found in IN",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    markets: {
        parameters: {
            query: {
                /** @description Area id */
                area: string;
                /** @description Country code */
                country: string;
            };
            header?: never;
            path: {
                /** @description Crop id */
                crop: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "crop_id": "onion",
                     *       "currency": "INR",
                     *       "median_per_kg": 23.5,
                     *       "rows": [
                     *         {
                     *           "diff_per_kg": 1.4,
                     *           "km_from_center": 88,
                     *           "market_id": "satana",
                     *           "name": {
                     *             "en": "Satana",
                     *             "zh-TW": "Satana"
                     *           },
                     *           "price_per_kg": 24.9,
                     *           "staleness": {
                     *             "days": 0,
                     *             "state": "today"
                     *           },
                     *           "trade_date": "2026-09-19"
                     *         }
                     *       ],
                     *       "staleness": {
                     *         "days": 0,
                     *         "state": "today"
                     *       },
                     *       "today": "2026-09-19",
                     *       "trade_date": "2026-09-19"
                     *     }
                     */
                    "application/json": components["schemas"]["MarketsOut"];
                };
            };
            /** @description type: Input should be 'wholesale' or 'retail' */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "type: Input should be 'wholesale' or 'retail'",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Area 'xyz' not found in IN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "area_not_found",
                     *         "message": "Area 'xyz' not found in IN",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    market: {
        parameters: {
            query: {
                /** @description Country code */
                country: string;
            };
            header?: never;
            path: {
                /** @description Crop id */
                crop: string;
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "change": {
                     *         "diff_per_kg": 0.95,
                     *         "direction": "up",
                     *         "pct": 0.042,
                     *         "prev_trade_date": "2026-09-18"
                     *       },
                     *       "crop_id": "onion",
                     *       "currency": "INR",
                     *       "fetched_at": "2026-09-19T11:40:00+05:30",
                     *       "high_per_kg": 26,
                     *       "km_from_center": 32,
                     *       "low_per_kg": 18.9,
                     *       "market_id": "lasalgaon",
                     *       "name": {
                     *         "en": "Lasalgaon",
                     *         "zh-TW": "Lasalgaon"
                     *       },
                     *       "price_per_kg": 23.4,
                     *       "source": {
                     *         "id": "mock",
                     *         "name": {
                     *           "en": "Demo data",
                     *           "zh-TW": "示範資料"
                     *         }
                     *       },
                     *       "staleness": {
                     *         "days": 0,
                     *         "state": "today"
                     *       },
                     *       "today": "2026-09-19",
                     *       "trade_date": "2026-09-19"
                     *     }
                     */
                    "application/json": components["schemas"]["MarketOut"];
                };
            };
            /** @description Market 'xyz' not found in IN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "market_not_found",
                     *         "message": "Market 'xyz' not found in IN",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote: {
        parameters: {
            query: {
                /** @description Area id */
                area: string;
                /** @description Country code */
                country: string;
                /** @description Series length */
                days?: number;
                /** @description wholesale or retail */
                type?: "wholesale" | "retail";
            };
            header?: never;
            path: {
                /** @description Crop id */
                crop: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "change": {
                     *         "diff_per_kg": 0.95,
                     *         "direction": "up",
                     *         "pct": 0.042,
                     *         "prev_trade_date": "2026-09-18"
                     *       },
                     *       "crop_id": "onion",
                     *       "currency": "INR",
                     *       "fetched_at": "2026-09-19T11:40:00+05:30",
                     *       "markets": {
                     *         "count": 7,
                     *         "max_per_kg": 24.9,
                     *         "min_per_kg": 22.8,
                     *         "total": 10
                     *       },
                     *       "nearby": {
                     *         "highest": {
                     *           "area_id": "pune",
                     *           "diff_per_kg": 0.8,
                     *           "distance_km": 165,
                     *           "is_base": false,
                     *           "price_per_kg": 24.3
                     *         },
                     *         "lowest": {
                     *           "area_id": "ahmednagar",
                     *           "diff_per_kg": -0.9,
                     *           "distance_km": 142,
                     *           "is_base": false,
                     *           "price_per_kg": 22.6
                     *         }
                     *       },
                     *       "price_per_kg": 23.5,
                     *       "series": [
                     *         {
                     *           "date": "2026-08-21",
                     *           "price_per_kg": 21.2
                     *         },
                     *         {
                     *           "date": "2026-08-23"
                     *         }
                     *       ],
                     *       "source": {
                     *         "id": "mock",
                     *         "name": {
                     *           "en": "Demo data",
                     *           "zh-TW": "示範資料"
                     *         }
                     *       },
                     *       "staleness": {
                     *         "days": 0,
                     *         "state": "today"
                     *       },
                     *       "stats": {
                     *         "arrivals": "high",
                     *         "arrivals_ratio": 1.18,
                     *         "change30_pct": 0.11,
                     *         "change7_pct": 0.052,
                     *         "high30_per_kg": 24.1,
                     *         "high7_per_kg": 23.5,
                     *         "low30_per_kg": 19.8,
                     *         "low7_per_kg": 21.9,
                     *         "pos30": 0.82,
                     *         "volatility": "mid",
                     *         "volatility_pct": 0.028,
                     *         "vs_avg7_pct": 0.031
                     *       },
                     *       "today": "2026-09-19",
                     *       "trade_date": "2026-09-19",
                     *       "type": "wholesale"
                     *     }
                     */
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description type: Input should be 'wholesale' or 'retail' */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "type: Input should be 'wholesale' or 'retail'",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Crop 'durian' not found in IN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "crop_not_found",
                     *         "message": "Crop 'durian' not found in IN",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "database": "ok",
                     *       "sources": [
                     *         {
                     *           "last_success_at": "2026-09-19T00:05:03+00:00",
                     *           "rows_ok": 26355,
                     *           "source": "mock"
                     *         }
                     *       ],
                     *       "status": "ok",
                     *       "version": "f40c282"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    intl_prices: {
        parameters: {
            query: {
                /** @description Country code; its currency is shown */
                country: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "country": "TW",
                     *       "currency": "TWD",
                     *       "fx": {
                     *         "currency": "TWD",
                     *         "per_usd": 31.834145,
                     *         "rate_date": "2026-09-19"
                     *       },
                     *       "items": [
                     *         {
                     *           "category": "cereal",
                     *           "change": {
                     *             "diff_per_kg": 0.1273,
                     *             "direction": "up",
                     *             "pct": 0.008565,
                     *             "prev_month": "2026-07-01"
                     *           },
                     *           "icon": "rice",
                     *           "id": "rice",
                     *           "month": "2026-08-01",
                     *           "name": {
                     *             "en": "Rice",
                     *             "zh-TW": "稻米"
                     *           },
                     *           "price_per_kg": 14.9939,
                     *           "source_name": "Rice, Thai 5%",
                     *           "spec": {
                     *             "en": "Thai 5% broken",
                     *             "zh-TW": "泰國 5% 碎米"
                     *           },
                     *           "usd": 471,
                     *           "usd_unit": "mt"
                     *         }
                     *       ],
                     *       "published": "2026-09-02",
                     *       "today": "2026-09-20"
                     *     }
                     */
                    "application/json": components["schemas"]["IntlPricesOut"];
                };
            };
            /** @description country: Field required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "country: Field required",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Country 'XX' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "country_not_found",
                     *         "message": "Country 'XX' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    intl_series: {
        parameters: {
            query: {
                /** @description Country code; its currency is shown */
                country: string;
            };
            header?: never;
            path: {
                /** @description Series id */
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "category": "cereal",
                     *       "change": {
                     *         "diff_per_kg": 0.1273,
                     *         "direction": "up",
                     *         "pct": 0.008565,
                     *         "prev_month": "2026-07-01"
                     *       },
                     *       "country": "TW",
                     *       "currency": "TWD",
                     *       "fx": {
                     *         "currency": "TWD",
                     *         "per_usd": 31.834145,
                     *         "rate_date": "2026-09-19"
                     *       },
                     *       "icon": "rice",
                     *       "id": "rice",
                     *       "month": "2026-08-01",
                     *       "name": {
                     *         "en": "Rice",
                     *         "zh-TW": "稻米"
                     *       },
                     *       "price_per_kg": 14.9939,
                     *       "published": "2026-09-02",
                     *       "series": [
                     *         {
                     *           "month": "2025-09-01",
                     *           "price_per_kg": 11.906,
                     *           "usd": 374
                     *         },
                     *         {
                     *           "month": "2026-08-01",
                     *           "price_per_kg": 14.9939,
                     *           "usd": 471
                     *         }
                     *       ],
                     *       "source_name": "Rice, Thai 5%",
                     *       "spec": {
                     *         "en": "Thai 5% broken",
                     *         "zh-TW": "泰國 5% 碎米"
                     *       },
                     *       "stats": {
                     *         "avg_per_kg": 13.251,
                     *         "high_per_kg": 15.726,
                     *         "low_per_kg": 11.333,
                     *         "vs_avg_pct": 0.131532
                     *       },
                     *       "today": "2026-09-20",
                     *       "usd": 471,
                     *       "usd_unit": "mt"
                     *     }
                     */
                    "application/json": components["schemas"]["IntlSeriesOut"];
                };
            };
            /** @description country: Field required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "country: Field required",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Series 'xyz' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "series_not_found",
                     *         "message": "Series 'xyz' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    locate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "country": "IN"
                     *     }
                     */
                    "application/json": components["schemas"]["LocateOut"];
                };
            };
        };
    };
    news: {
        parameters: {
            query: {
                /** @description The user's area, listed first */
                area: string;
                /** @description Country code */
                country: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "yunlin",
                     *       "country": "TW",
                     *       "fetched_at": "2026-09-20T00:03:12+08:00",
                     *       "items": [
                     *         {
                     *           "area_ids": [
                     *             "yunlin"
                     *           ],
                     *           "crop_ids": [
                     *             "bokchoy",
                     *             "cabbage"
                     *           ],
                     *           "days_ago": 6,
                     *           "id": 12,
                     *           "lang": "zh-TW",
                     *           "published_at": "2026-09-14T15:00:00+08:00",
                     *           "published_date": "2026-09-14",
                     *           "source": {
                     *             "domain": "news.pts.org.tw",
                     *             "name": "公視新聞網PNN"
                     *           },
                     *           "summary": "西螺果菜市場蔬菜到貨量減至約720公噸，平均每公斤約50元，比半個月前漲約3成。市場預估還要約10天，復耕的葉菜上市後價格才會回穩。",
                     *           "summary_lang": "zh-TW",
                     *           "title": "連續降雨全台農損逾2.3億 西螺果菜市場菜價漲3成",
                     *           "url": "https://news.pts.org.tw/article/825149"
                     *         }
                     *       ],
                     *       "today": "2026-09-20"
                     *     }
                     */
                    "application/json": components["schemas"]["NewsOut"];
                };
            };
            /** @description country: Field required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "country: Field required",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Area 'xyz' not found in TW */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "area_not_found",
                     *         "message": "Area 'xyz' not found in TW",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description News item id */
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_ids": [
                     *         "yunlin"
                     *       ],
                     *       "country": "TW",
                     *       "crop_ids": [
                     *         "bokchoy",
                     *         "cabbage"
                     *       ],
                     *       "days_ago": 6,
                     *       "id": 12,
                     *       "lang": "zh-TW",
                     *       "published_at": "2026-09-14T15:00:00+08:00",
                     *       "published_date": "2026-09-14",
                     *       "source": {
                     *         "domain": "news.pts.org.tw",
                     *         "name": "公視新聞網PNN"
                     *       },
                     *       "summary": "西螺果菜市場蔬菜到貨量減至約720公噸，平均每公斤約50元，比半個月前漲約3成。市場預估還要約10天，復耕的葉菜上市後價格才會回穩。",
                     *       "summary_lang": "zh-TW",
                     *       "title": "連續降雨全台農損逾2.3億 西螺果菜市場菜價漲3成",
                     *       "today": "2026-09-20",
                     *       "url": "https://news.pts.org.tw/article/825149"
                     *     }
                     */
                    "application/json": components["schemas"]["NewsItemDetailOut"];
                };
            };
            /** @description News item 12 not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "news_not_found",
                     *         "message": "News item 12 not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices: {
        parameters: {
            query: {
                /** @description Area id */
                area: string;
                /** @description Country code */
                country: string;
                crops?: string | null;
                /** @description wholesale or retail */
                type?: "wholesale" | "retail";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "area_id": "nashik",
                     *       "country": "IN",
                     *       "currency": "INR",
                     *       "fetched_at": "2026-09-19T11:40:00+05:30",
                     *       "items": [
                     *         {
                     *           "change": {
                     *             "diff_per_kg": 0.95,
                     *             "direction": "up",
                     *             "pct": 0.042,
                     *             "prev_trade_date": "2026-09-18"
                     *           },
                     *           "crop_id": "onion",
                     *           "price_per_kg": 23.5,
                     *           "spark": [
                     *             null,
                     *             22.1,
                     *             22.3,
                     *             22,
                     *             22.4,
                     *             22.55,
                     *             23.5
                     *           ],
                     *           "staleness": {
                     *             "days": 0,
                     *             "state": "today"
                     *           },
                     *           "trade_date": "2026-09-19"
                     *         },
                     *         {
                     *           "crop_id": "chilli",
                     *           "reason": "no_retail_crop",
                     *           "spark": [
                     *             null,
                     *             null,
                     *             null,
                     *             null,
                     *             null,
                     *             null,
                     *             null
                     *           ],
                     *           "staleness": {
                     *             "state": "none"
                     *           }
                     *         }
                     *       ],
                     *       "today": "2026-09-19",
                     *       "type": "wholesale"
                     *     }
                     */
                    "application/json": components["schemas"]["PricesOut"];
                };
            };
            /** @description type: Input should be 'wholesale' or 'retail' */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_param",
                     *         "message": "type: Input should be 'wholesale' or 'retail'",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Area 'xyz' not found in IN */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "area_not_found",
                     *         "message": "Area 'xyz' not found in IN",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Simulated failure (X-Demo-Fail, demo mode only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "demo_failure",
                     *         "message": "Simulated failure (X-Demo-Fail, demo mode only)",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
