/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Countries and their settings
         * @description Currency, locale, local today, closed weekdays (ISO, 7 = Sunday), rise colour (`up_is_pos`: rising prices shown green), default area, recent areas and watchlist, and the unit table (per-kg factor and decimals) for wholesale and retail.
         */
        get: operations["countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{cc}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Areas of a country
         * @description Areas (district or city) with centre coordinates for straight-line distances, whether retail prices are reported, and the latest wholesale trade date with its freshness.
         */
        get: operations["areas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{cc}/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crops of a country
         * @description Names, category, variety, whether retail prices exist, default watchlist.
         */
        get: operations["crops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Database status and the latest successful fetch of every data source. Returns 503 `db_unavailable` when the database is down.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaOut */
        AreaOut: {
            /** Has Retail */
            has_retail: boolean;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Latest Trade Date */
            latest_trade_date: string | null;
            /** Lon */
            lon: number;
            name: components["schemas"]["I18nText"];
            region: components["schemas"]["I18nText"];
            staleness: components["schemas"]["StalenessOut"];
        };
        /** AreasOut */
        AreasOut: {
            /** Areas */
            areas: components["schemas"]["AreaOut"][];
            /** Country */
            country: string;
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /** CountriesOut */
        CountriesOut: {
            /** Countries */
            countries: components["schemas"]["CountryOut"][];
        };
        /** CountryOut */
        CountryOut: {
            area_suffix: components["schemas"]["I18nText"];
            /** Closed Weekdays */
            closed_weekdays: number[];
            /** Code */
            code: string;
            coverage: components["schemas"]["I18nText"];
            /** Currency */
            currency: string;
            /** Default Area Id */
            default_area_id: string;
            /** Default Recent Area Ids */
            default_recent_area_ids: string[];
            /** Default Watch */
            default_watch: string[];
            /** Locale */
            locale: string;
            name: components["schemas"]["I18nText"];
            rep_price_label: components["schemas"]["I18nText"];
            source_label: components["schemas"]["I18nText"];
            /**
             * Today
             * Format: date
             */
            today: string;
            units: components["schemas"]["UnitsOut"];
            /** Up Is Pos */
            up_is_pos: boolean;
            /** Utc Offset Min */
            utc_offset_min: number;
        };
        /** CropOut */
        CropOut: {
            /** Category */
            category: string;
            /** Default Watch */
            default_watch: boolean;
            /** Has Retail */
            has_retail: boolean;
            /** Id */
            id: string;
            name: components["schemas"]["I18nText"];
            variety: components["schemas"]["I18nText"];
        };
        /** CropsOut */
        CropsOut: {
            /** Country */
            country: string;
            /** Crops */
            crops: components["schemas"]["CropOut"][];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Sources */
            sources: components["schemas"]["SourceStatusOut"][];
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * I18nText
         * @description Text in every supported language; switching language needs no refetch.
         */
        I18nText: {
            /** En */
            en: string;
            /** Zh-Tw */
            "zh-TW": string;
        };
        /** SourceStatusOut */
        SourceStatusOut: {
            /**
             * Last Success At
             * Format: date-time
             */
            last_success_at: string;
            /** Rows Ok */
            rows_ok: number;
            /** Source */
            source: string;
        };
        /**
         * StalenessOut
         * @description today · closed (only closed days since) · stale · none (nothing in 30 days).
         */
        StalenessOut: {
            /** Days */
            days: number | null;
            /** State */
            state: string;
        };
        /** UnitOptionOut */
        UnitOptionOut: {
            /** Decimals */
            decimals: number;
            /** Id */
            id: string;
            label: components["schemas"]["I18nText"];
            /** Per Kg */
            per_kg: number;
        };
        /** UnitSetOut */
        UnitSetOut: {
            /** Default */
            default: string;
            /** Options */
            options: components["schemas"]["UnitOptionOut"][];
        };
        /** UnitsOut */
        UnitsOut: {
            retail: components["schemas"]["UnitSetOut"];
            wholesale: components["schemas"]["UnitSetOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAreaOut = components['schemas']['AreaOut'];
export type SchemaAreasOut = components['schemas']['AreasOut'];
export type SchemaCountriesOut = components['schemas']['CountriesOut'];
export type SchemaCountryOut = components['schemas']['CountryOut'];
export type SchemaCropOut = components['schemas']['CropOut'];
export type SchemaCropsOut = components['schemas']['CropsOut'];
export type SchemaErrorBody = components['schemas']['ErrorBody'];
export type SchemaErrorOut = components['schemas']['ErrorOut'];
export type SchemaHealthOut = components['schemas']['HealthOut'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaI18nText = components['schemas']['I18nText'];
export type SchemaSourceStatusOut = components['schemas']['SourceStatusOut'];
export type SchemaStalenessOut = components['schemas']['StalenessOut'];
export type SchemaUnitOptionOut = components['schemas']['UnitOptionOut'];
export type SchemaUnitSetOut = components['schemas']['UnitSetOut'];
export type SchemaUnitsOut = components['schemas']['UnitsOut'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "countries": [
                     *         {
                     *           "area_suffix": {
                     *             "en": " district",
                     *             "zh-TW": " 縣"
                     *           },
                     *           "closed_weekdays": [
                     *             7
                     *           ],
                     *           "code": "IN",
                     *           "coverage": {
                     *             "en": "6 states, 11 districts",
                     *             "zh-TW": "6 個邦、11 個縣"
                     *           },
                     *           "currency": "INR",
                     *           "default_area_id": "nashik",
                     *           "default_recent_area_ids": [
                     *             "nashik",
                     *             "pune",
                     *             "ahmednagar"
                     *           ],
                     *           "default_watch": [
                     *             "onion",
                     *             "tomato",
                     *             "potato"
                     *           ],
                     *           "locale": "en-IN",
                     *           "name": {
                     *             "en": "India",
                     *             "zh-TW": "印度"
                     *           },
                     *           "rep_price_label": {
                     *             "en": "Modal price",
                     *             "zh-TW": "常見價"
                     *           },
                     *           "source_label": {
                     *             "en": "Agmarknet",
                     *             "zh-TW": "Agmarknet・消費者事務部（印度政府）"
                     *           },
                     *           "today": "2026-09-19",
                     *           "units": {
                     *             "retail": {
                     *               "default": "kg",
                     *               "options": [
                     *                 {
                     *                   "decimals": 1,
                     *                   "id": "kg",
                     *                   "label": {
                     *                     "en": "₹/kg",
                     *                     "zh-TW": "₹/公斤"
                     *                   },
                     *                   "per_kg": 1
                     *                 },
                     *                 {
                     *                   "decimals": 0,
                     *                   "id": "qtl",
                     *                   "label": {
                     *                     "en": "₹/qtl",
                     *                     "zh-TW": "₹/公擔"
                     *                   },
                     *                   "per_kg": 100
                     *                 }
                     *               ]
                     *             },
                     *             "wholesale": {
                     *               "default": "qtl",
                     *               "options": [
                     *                 {
                     *                   "decimals": 0,
                     *                   "id": "qtl",
                     *                   "label": {
                     *                     "en": "₹/qtl",
                     *                     "zh-TW": "₹/公擔"
                     *                   },
                     *                   "per_kg": 100
                     *                 },
                     *                 {
                     *                   "decimals": 1,
                     *                   "id": "kg",
                     *                   "label": {
                     *                     "en": "₹/kg",
                     *                     "zh-TW": "₹/公斤"
                     *                   },
                     *                   "per_kg": 1
                     *                 }
                     *               ]
                     *             }
                     *           },
                     *           "up_is_pos": true,
                     *           "utc_offset_min": 330
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CountriesOut"];
                };
            };
        };
    };
    areas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Country code, e.g. `IN` or `TW` */
                cc: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "areas": [
                     *         {
                     *           "has_retail": true,
                     *           "id": "nashik",
                     *           "lat": 20,
                     *           "latest_trade_date": "2026-09-19",
                     *           "lon": 73.79,
                     *           "name": {
                     *             "en": "Nashik",
                     *             "zh-TW": "Nashik"
                     *           },
                     *           "region": {
                     *             "en": "Maharashtra",
                     *             "zh-TW": "Maharashtra"
                     *           },
                     *           "staleness": {
                     *             "days": 0,
                     *             "state": "today"
                     *           }
                     *         },
                     *         {
                     *           "has_retail": false,
                     *           "id": "kolar",
                     *           "lat": 13.14,
                     *           "latest_trade_date": "2026-09-16",
                     *           "lon": 78.13,
                     *           "name": {
                     *             "en": "Kolar",
                     *             "zh-TW": "Kolar"
                     *           },
                     *           "region": {
                     *             "en": "Karnataka",
                     *             "zh-TW": "Karnataka"
                     *           },
                     *           "staleness": {
                     *             "days": 3,
                     *             "state": "stale"
                     *           }
                     *         }
                     *       ],
                     *       "country": "IN",
                     *       "today": "2026-09-19"
                     *     }
                     */
                    "application/json": components["schemas"]["AreasOut"];
                };
            };
            /** @description Country 'XX' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "country_not_found",
                     *         "message": "Country 'XX' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Country code, e.g. `IN` or `TW` */
                cc: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "country": "IN",
                     *       "crops": [
                     *         {
                     *           "category": "veg",
                     *           "default_watch": true,
                     *           "has_retail": true,
                     *           "id": "onion",
                     *           "name": {
                     *             "en": "Onion",
                     *             "zh-TW": "洋蔥"
                     *           },
                     *           "variety": {
                     *             "en": "Red",
                     *             "zh-TW": "紅洋蔥"
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["CropsOut"];
                };
            };
            /** @description Country 'XX' not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "country_not_found",
                     *         "message": "Country 'XX' not found",
                     *         "request_id": "b3f1c2…"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "database": "ok",
                     *       "sources": [
                     *         {
                     *           "last_success_at": "2026-09-19T00:05:03+00:00",
                     *           "rows_ok": 26355,
                     *           "source": "mock"
                     *         }
                     *       ],
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
