"""record requests and files per ingest run

Revision ID: 74f6aadac0c6
Revises: 80ac1f2d0366
Create Date: 2026-09-20 03:39:00.155764
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '74f6aadac0c6'
down_revision: str | Sequence[str] | None = '80ac1f2d0366'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingest_runs', sa.Column('requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingest_runs', sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('ingest_runs', sa.Column('maps_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingest_runs', 'maps_hash')
    op.drop_column('ingest_runs', 'files')
    op.drop_column('ingest_runs', 'requests')
    # ### end Alembic commands ###
