"""add news tables

News items and news runs for the 新聞 page (docs/04 §7). Self-contained: it only creates and
drops its own two tables, so it can be re-chained after other migrations.

Revision ID: 23655d2e487a
Revises: 74f6aadac0c6
Create Date: 2026-09-20 03:58:40.805118
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '23655d2e487a'
down_revision: str | Sequence[str] | None = '74f6aadac0c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('items_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_new', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('articles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summaries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name='ck_news_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_runs_country_started', 'news_runs', ['country', 'source', 'started_at'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('guid', sa.String(length=400), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_key', sa.String(length=200), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_domain', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_lang', sa.String(length=10), nullable=True),
    sa.Column('summary_model', sa.String(length=80), nullable=True),
    sa.Column('summary_tries', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('crop_ids', sa.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('area_ids', sa.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'guid', name='uq_news_items_guid'),
    sa.UniqueConstraint('country', 'title_key', name='uq_news_items_title')
    )
    op.create_index('ix_news_items_country_published', 'news_items', ['country', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_items_country_published', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_news_runs_country_started', table_name='news_runs')
    op.drop_table('news_runs')
    # ### end Alembic commands ###
