"""add intl prices

Bonus B5 (international reference prices): World Bank Pink Sheet series, their monthly
prices, the daily exchange rates and the download state of both sources. Only new tables,
so it can be re-chained after other migrations without changes.

Revision ID: 80ac1f2d0366
Revises: bec1dda1df2f
Create Date: 2026-09-20 03:49:45.477032
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '80ac1f2d0366'
down_revision: str | Sequence[str] | None = 'bec1dda1df2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('per_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('per_usd > 0', name='ck_fx_rates_positive'),
    sa.PrimaryKeyConstraint('currency')
    )
    op.create_table('intl_series',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.Column('source_column', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=4), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("unit IN ('mt', 'kg')", name='ck_intl_series_unit'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intl_sources',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('next_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intl_prices',
    sa.Column('series_id', sa.String(length=20), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('usd', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name='ck_intl_prices_first_day'),
    sa.CheckConstraint('usd > 0', name='ck_intl_prices_usd_positive'),
    sa.ForeignKeyConstraint(['series_id'], ['intl_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intl_prices')
    op.drop_table('intl_sources')
    op.drop_table('intl_series')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
