"""add country source label

Revision ID: bec1dda1df2f
Revises: a0598147c85d
Create Date: 2026-09-19 19:46:17.454449
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bec1dda1df2f'
down_revision: str | Sequence[str] | None = 'a0598147c85d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows get an empty object; the seed sync fills the real label.
    op.add_column(
        'countries',
        sa.Column(
            'source_label',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column('countries', 'source_label', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'source_label')
    # ### end Alembic commands ###
