"""create tables

Revision ID: a0598147c85d
Revises: 
Create Date: 2026-09-19 19:43:09.142628
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a0598147c85d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('utc_offset_min', sa.SmallInteger(), nullable=False),
    sa.Column('up_is_pos', sa.Boolean(), nullable=False),
    sa.Column('closed_weekdays', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('default_area_id', sa.String(length=40), nullable=False),
    sa.Column('default_recent_area_ids', sa.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('area_suffix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rep_price_label', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('units', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('rows_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_ok', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_dropped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drop_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'ok', 'failed')", name='ck_ingest_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_runs_source_started', 'ingest_runs', ['source', 'started_at'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('region', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('has_retail', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_areas_country', 'areas', ['country'], unique=False)
    op.create_table('crops',
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('variety', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.Column('default_watch', sa.Boolean(), nullable=False),
    sa.Column('has_retail', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['countries.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country', 'id')
    )
    op.create_table('area_daily',
    sa.Column('area_id', sa.String(length=40), nullable=False),
    sa.Column('crop_id', sa.String(length=40), nullable=False),
    sa.Column('price_type', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('n_markets', sa.SmallInteger(), nullable=False),
    sa.Column('min_market', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_market', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_kg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("price_type IN ('wholesale', 'retail')", name='ck_area_daily_price_type'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country', 'crop_id'], ['crops.country', 'crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id', 'crop_id', 'price_type', 'trade_date')
    )
    op.create_index('ix_area_daily_compare', 'area_daily', ['country', 'crop_id', 'price_type', 'trade_date'], unique=False)
    op.create_index('ix_area_daily_lookup', 'area_daily', ['area_id', 'crop_id', 'price_type', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('area_id', sa.String(length=40), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('km_from_center', sa.SmallInteger(), nullable=True),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_markets_area', 'markets', ['area_id'], unique=False)
    op.create_table('source_area_map',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source_area', sa.String(length=80), nullable=False),
    sa.Column('area_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source', 'country', 'source_area')
    )
    op.create_table('source_crop_map',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_variety', sa.String(length=80), server_default='', nullable=False),
    sa.Column('crop_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['country', 'crop_id'], ['crops.country', 'crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source', 'country', 'source_name', 'source_variety')
    )
    op.create_table('market_daily',
    sa.Column('market_id', sa.String(length=40), nullable=False),
    sa.Column('crop_id', sa.String(length=40), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('area_id', sa.String(length=40), nullable=False),
    sa.Column('rep_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_kg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country', 'crop_id'], ['crops.country', 'crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'crop_id', 'trade_date')
    )
    op.create_index('ix_market_daily_area_crop_date', 'market_daily', ['area_id', 'crop_id', 'trade_date'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('price_type', sa.String(length=10), nullable=False),
    sa.Column('market_id', sa.String(length=40), nullable=True),
    sa.Column('area_id', sa.String(length=40), nullable=False),
    sa.Column('crop_id', sa.String(length=40), nullable=False),
    sa.Column('variety', sa.String(length=80), server_default='', nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('rep_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_kg', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(price_type = 'wholesale') = (market_id IS NOT NULL)", name='ck_quotes_market_by_type'),
    sa.CheckConstraint("price_type IN ('wholesale', 'retail')", name='ck_quotes_price_type'),
    sa.CheckConstraint('rep_price > 0', name='ck_quotes_rep_positive'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country', 'crop_id'], ['crops.country', 'crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingest_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'price_type', 'area_id', 'market_id', 'crop_id', 'variety', 'trade_date', name='uq_quotes_source_key', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_quotes_crop_date', 'quotes', ['country', 'crop_id', 'trade_date'], unique=False)
    op.create_table('source_market_map',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('source_market', sa.String(length=80), nullable=False),
    sa.Column('market_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source', 'country', 'source_market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_market_map')
    op.drop_index('ix_quotes_crop_date', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_market_daily_area_crop_date', table_name='market_daily')
    op.drop_table('market_daily')
    op.drop_table('source_crop_map')
    op.drop_table('source_area_map')
    op.drop_index('ix_markets_area', table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_area_daily_lookup', table_name='area_daily')
    op.drop_index('ix_area_daily_compare', table_name='area_daily')
    op.drop_table('area_daily')
    op.drop_table('crops')
    op.drop_index('ix_areas_country', table_name='areas')
    op.drop_table('areas')
    op.drop_index('ix_ingest_runs_source_started', table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_table('countries')
    # ### end Alembic commands ###
